### PR TITLE
redefine partner and portal AAD "domain" as Tenant ID

### PR DESCRIPTION
**Pull request by lochiiconnectivity**
Fixes issue #2 by redefining 'domain' as 'ID'

### CODE REVIEW

**Comment by RaedJarrar** [comment]
In your changes, can you prefix your IDs with tenant to make it more specific? For example: webPortalId becomes webPortalAadTenantId and so forth

**Comment by lochiiconnectivity** [comment]
done.

**Comment by RaedJarrar** [comment]
Some file are not quite fixed such as: Startup.Auth.cs and CustomerPortalPrincipal. Please ensure tenant is added to all places.

**Comment by lochiiconnectivity** [comment]
Ack, didn't consider the internal reference , have amended and squashed down to original commit.

**Comment by RaedJarrar** [comment]
The changes look good. Did you build and test both the web application and the deployment project?

**Comment by lochiiconnectivity** [comment]
yes, and I have it deployed right now.

**Comment by RaedJarrar** [comment]
Thanks David for the changes. These are now checked in.

**Pull request merged**
